name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main # Adjust this to your default branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Adjust the version if needed

    - name: Install required packages
      run: |
        pip install requests

    - name: Upload all files to PythonAnywhere
      env:
        PA_API_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
        PA_USERNAME: saadkarim754
      run: |
        for file in $(find . -type f); do
          curl -X POST "https://www.pythonanywhere.com/api/v0/user/$PA_USERNAME/files/home/$PA_USERNAME/pss/${file}" \
          -H "Authorization: Token $PA_API_TOKEN" \
          -F "content=@$file"
        done

    - name: Reload PythonAnywhere Web App
      env:
        PA_API_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
        PA_USERNAME: saadkarim754
      run: |
        curl -X POST "https://www.pythonanywhere.com/api/v0/user/$PA_USERNAME/webapps/reload" \
        -H "Authorization: Token $PA_API_TOKEN"
